apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: k8s-monitoring
      targetRevision: 2.0.0
      helm:
        valueFiles:
          - $values/helm/alloy/values.yaml
    - repoURL: https://github.com/ryansissom/kubernetes-platform.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true